import React from "react"
import Navigation from "./Navigation"
import contact from "./pages/Contact"
import About from "./pages/About"
import Portfolio from "./pages/Portfolio"
import Resume from "./pages/Resume"